description: "Test sample"

prompts:
  - ../prompts/small.csv

providers:
  - "openai:gpt-4o-mini"

tests:
  - description: Evaluate securety considurations from LLM output based on prompt prefix 
    assert:
      - type: llm-rubric
        value: Ensure that the output is taking security considerations into account. For example any code should not have environment variables directly in the code. One should connect to APIs and services securely. Relevant code should parameterize queries. And there should as a rule not be any security implications unless they are justified and noted explicitly in the output.
